version: 0.2
env:
  # variables:
  #   key: "value"
  #   key: "value"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 600878681787.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t abbas-project-ecr .
      - docker tag abbas-project-ecr:latest 600878681787.dkr.ecr.us-west-2.amazonaws.com/abbas-project-ecr:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 600878681787.dkr.ecr.us-west-2.amazonaws.com/abbas-project-ecr:latest
      - echo write definitions file...
      - printf '[{"name":"abbas-project-ecs-container","imageUri":"%s"}]' 600878681787.dkr.ecr.us-west-2.amazonaws.com/abbas-project-ecr:latest > imagedefinitions.json
artifacts:
  files: '**/*'
